1CREATE DATABASE FOOD_ORDER
USE FOOD_ORDER

CREATE TABLE FoodItem(
	URL_FOOD_PICTURE VARCHAR(250),
	FOOD_NAME NVARCHAR(100),
	FOOD_ID VARCHAR(3) NOT NULL,
	FOOD_NUM_ORDER INT,
	FOOD_PRICES INT,
	FOOD_TYPE VARCHAR(8),

	PRIMARY KEY(FOOD_ID),
)

CREATE TABLE KHACHHANG(
	KH_NAME VARCHAR(50),
	KH_ID VARCHAR(5) NOT NULL,
	KH_PHONE_NUMBER VARCHAR(10),
	KH_ADDRESS VARCHAR(255),
	PRIMARY KEY(KH_ID),
)

CREATE TABLE FOOD_ORDERED(
	F_NAME VARCHAR(250),
	F_ID VARCHAR(3) NOT NULL,
	F_NUM_ORDER INT,
	F_PRICES INT,
	F_TYPE VARCHAR(8),
	F_TOTAL INT,

)

ALTER TABLE FOOD_ORDERED
ADD F_GHICHU VARCHAR(250)

ALTER TABLE FOOD_ORDERED
ADD MAKH VARCHAR(5)

ALTER TABLE FOOD_ORDERED
ALTER COLUMN MAKH VARCHAR(10) 

ALTER TABLE FOOD_ORDERED
DROP COLUMN F_TOTAL 

ALTER TABLE FOOD_ORDERED
ADD F_TOTAL AS F_NUM_ORDER * F_PRICES

UPDATE FOOD_ORDERED
SET F_TOTAL = F_NUM_ORDER*F_PRICES



INSERT INTO FoodItem (FOOD_ID,FOOD_NAME,FOOD_TYPE,FOOD_PRICES,FOOD_NUM_ORDER,URL_FOOD_PICTURE)  VALUES ('001',N'Mì Pasta Dẹt Với đĩa Sốt Xanh','FOOD',35000,0,CONCAT('P:\CS511\BTH\Drugstore\WindowsFormsApp1\Food_Picture\','pic1.jpg'))
INSERT INTO FoodItem (FOOD_ID,FOOD_NAME,FOOD_TYPE,FOOD_PRICES,FOOD_NUM_ORDER,URL_FOOD_PICTURE)  VALUES ('002',N'Canh Chua Cá Lóc','FOOD',30000,0,CONCAT('P:\CS511\BTH\Drugstore\WindowsFormsApp1\Food_Picture\','pic2.jpg'))
INSERT INTO FoodItem (FOOD_ID,FOOD_NAME,FOOD_TYPE,FOOD_PRICES,FOOD_NUM_ORDER,URL_FOOD_PICTURE)  VALUES ('003',N'Sườn Xào Chua Ngọt','FOOD',30000,0,CONCAT('P:\CS511\BTH\Drugstore\WindowsFormsApp1\Food_Picture\','pic3.jpg'))
INSERT INTO FoodItem (FOOD_ID,FOOD_NAME,FOOD_TYPE,FOOD_PRICES,FOOD_NUM_ORDER,URL_FOOD_PICTURE)  VALUES ('004',N'Hủ Tiếu Nam Vang','FOOD',25000,0,CONCAT('P:\CS511\BTH\Drugstore\WindowsFormsApp1\Food_Picture\','pic4.jpg'))
INSERT INTO FoodItem (FOOD_ID,FOOD_NAME,FOOD_TYPE,FOOD_PRICES,FOOD_NUM_ORDER,URL_FOOD_PICTURE)  VALUES ('005',N'Mì Quảng','FOOD',35000,0,CONCAT('P:\CS511\BTH\Drugstore\WindowsFormsApp1\Food_Picture\','pic5.jpg'))
INSERT INTO FoodItem (FOOD_ID,FOOD_NAME,FOOD_TYPE,FOOD_PRICES,FOOD_NUM_ORDER,URL_FOOD_PICTURE)  VALUES ('006',N'Bánh Bao','FOOD',30000,0,CONCAT('P:\CS511\BTH\Drugstore\WindowsFormsApp1\Food_Picture\','pic6.jpg'))
INSERT INTO FoodItem (FOOD_ID,FOOD_NAME,FOOD_TYPE,FOOD_PRICES,FOOD_NUM_ORDER,URL_FOOD_PICTURE)  VALUES ('007',N'Bánh Cuốn','FOOD',20000,0,CONCAT('P:\CS511\BTH\Drugstore\WindowsFormsApp1\Food_Picture\','pic7.jpg'))
INSERT INTO FoodItem (FOOD_ID,FOOD_NAME,FOOD_TYPE,FOOD_PRICES,FOOD_NUM_ORDER,URL_FOOD_PICTURE)  VALUES ('008',N'Phở Bò','FOOD',25000,0,CONCAT('P:\CS511\BTH\Drugstore\WindowsFormsApp1\Food_Picture\','pic8.jpg'))
INSERT INTO FoodItem (FOOD_ID,FOOD_NAME,FOOD_TYPE,FOOD_PRICES,FOOD_NUM_ORDER,URL_FOOD_PICTURE)  VALUES ('009',N'bánh Mì Thịt Nướng','FOOD',20000,0,CONCAT('P:\CS511\BTH\Drugstore\WindowsFormsApp1\Food_Picture\','pic9.jpg'))
INSERT INTO FoodItem (FOOD_ID,FOOD_NAME,FOOD_TYPE,FOOD_PRICES,FOOD_NUM_ORDER,URL_FOOD_PICTURE)  VALUES ('010',N'Rau Xiên Ớt Cựa Gà','FOOD',25000,0,CONCAT('P:\CS511\BTH\Drugstore\WindowsFormsApp1\Food_Picture\','pic10.jpg'))
INSERT INTO FoodItem (FOOD_ID,FOOD_NAME,FOOD_TYPE,FOOD_PRICES,FOOD_NUM_ORDER,URL_FOOD_PICTURE)  VALUES ('011',N'Pizza Phô Mai','FOOD',35000,0,CONCAT('P:\CS511\BTH\Drugstore\WindowsFormsApp1\Food_Picture\','pic11.jpg'))
INSERT INTO FoodItem (FOOD_ID,FOOD_NAME,FOOD_TYPE,FOOD_PRICES,FOOD_NUM_ORDER,URL_FOOD_PICTURE)  VALUES ('012',N'Bánh Xèo Schaumomelette','FOOD',30000,0,CONCAT('P:\CS511\BTH\Drugstore\WindowsFormsApp1\Food_Picture\','pic12.jpg'))
INSERT INTO FoodItem (FOOD_ID,FOOD_NAME,FOOD_TYPE,FOOD_PRICES,FOOD_NUM_ORDER,URL_FOOD_PICTURE)  VALUES ('013',N'Măng Tây Miếng Bò Hầm','FOOD',30000,0,CONCAT('P:\CS511\BTH\Drugstore\WindowsFormsApp1\Food_Picture\','pic13.jpg'))
INSERT INTO FoodItem (FOOD_ID,FOOD_NAME,FOOD_TYPE,FOOD_PRICES,FOOD_NUM_ORDER,URL_FOOD_PICTURE)  VALUES ('014',N'Cá Hồi Hải Sản','FOOD',35000,0,CONCAT('P:\CS511\BTH\Drugstore\WindowsFormsApp1\Food_Picture\','pic14.jpg'))
INSERT INTO FoodItem (FOOD_ID,FOOD_NAME,FOOD_TYPE,FOOD_PRICES,FOOD_NUM_ORDER,URL_FOOD_PICTURE)  VALUES ('015',N'Mỳ Ý sốt thịt bò','FOOD',30000,0,CONCAT('P:\CS511\BTH\Drugstore\WindowsFormsApp1\Food_Picture\','pic15.jpg'))
INSERT INTO FoodItem (FOOD_ID,FOOD_NAME,FOOD_TYPE,FOOD_PRICES,FOOD_NUM_ORDER,URL_FOOD_PICTURE)  VALUES ('016',N'Cá Thu sốt cà chua','FOOD',25000,0,CONCAT('P:\CS511\BTH\Drugstore\WindowsFormsApp1\Food_Picture\','pic16.jpg'))
INSERT INTO FoodItem (FOOD_ID,FOOD_NAME,FOOD_TYPE,FOOD_PRICES,FOOD_NUM_ORDER,URL_FOOD_PICTURE)  VALUES ('017',N'Trà Xanh Xoài','BEVERAGE',25000,0,CONCAT('P:\CS511\BTH\Drugstore\WindowsFormsApp1\Food_Picture\','pic17.jpg'))
INSERT INTO FoodItem (FOOD_ID,FOOD_NAME,FOOD_TYPE,FOOD_PRICES,FOOD_NUM_ORDER,URL_FOOD_PICTURE)  VALUES ('018',N'Trà Xanh Kem Phô Mai','BEVERAGE',30000,0,CONCAT('P:\CS511\BTH\Drugstore\WindowsFormsApp1\Food_Picture\','pic18.jpg'))
INSERT INTO FoodItem (FOOD_ID,FOOD_NAME,FOOD_TYPE,FOOD_PRICES,FOOD_NUM_ORDER,URL_FOOD_PICTURE)  VALUES ('019',N'Hồng Trà Kem Phô Mai','BEVERAGE',30000,0,CONCAT('P:\CS511\BTH\Drugstore\WindowsFormsApp1\Food_Picture\','pic19.jpg'))
INSERT INTO FoodItem (FOOD_ID,FOOD_NAME,FOOD_TYPE,FOOD_PRICES,FOOD_NUM_ORDER,URL_FOOD_PICTURE)  VALUES ('020',N'Dâu Tằm Kem Phô Mai','BEVERAGE',30000,0,CONCAT('P:\CS511\BTH\Drugstore\WindowsFormsApp1\Food_Picture\','pic20.jpg'))
INSERT INTO FoodItem (FOOD_ID,FOOD_NAME,FOOD_TYPE,FOOD_PRICES,FOOD_NUM_ORDER,URL_FOOD_PICTURE)  VALUES ('021',N'Tiger Sugar','BEVERAGE',35000,0,CONCAT('P:\CS511\BTH\Drugstore\WindowsFormsApp1\Food_Picture\','pic21.jpg'))
INSERT INTO FoodItem (FOOD_ID,FOOD_NAME,FOOD_TYPE,FOOD_PRICES,FOOD_NUM_ORDER,URL_FOOD_PICTURE)  VALUES ('022',N'Trà Sữa Trân Châu Hoàng Gia','BEVERAGE',45000,0,CONCAT('P:\CS511\BTH\Drugstore\WindowsFormsApp1\Food_Picture\','pic22.jpg'))
INSERT INTO FoodItem (FOOD_ID,FOOD_NAME,FOOD_TYPE,FOOD_PRICES,FOOD_NUM_ORDER,URL_FOOD_PICTURE)  VALUES ('023',N'Trà Sữa Ba Anh Em','BEVERAGE',40000,0,CONCAT('P:\CS511\BTH\Drugstore\WindowsFormsApp1\Food_Picture\','pic23.jpg'))
INSERT INTO FoodItem (FOOD_ID,FOOD_NAME,FOOD_TYPE,FOOD_PRICES,FOOD_NUM_ORDER,URL_FOOD_PICTURE)  VALUES ('024',N'Trà Sữa Panda','BEVERAGE',40000,0,CONCAT('P:\CS511\BTH\Drugstore\WindowsFormsApp1\Food_Picture\','pic24.jpg'))
INSERT INTO FoodItem (FOOD_ID,FOOD_NAME,FOOD_TYPE,FOOD_PRICES,FOOD_NUM_ORDER,URL_FOOD_PICTURE)  VALUES ('025',N'Trà Sữa Kim Cương Đen','BEVERAGE',35000,0,CONCAT('P:\CS511\BTH\Drugstore\WindowsFormsApp1\Food_Picture\','pic25.jpg'))
INSERT INTO FoodItem (FOOD_ID,FOOD_NAME,FOOD_TYPE,FOOD_PRICES,FOOD_NUM_ORDER,URL_FOOD_PICTURE)  VALUES ('026',N'Trà Dừa Nhiệt Đới','BEVERAGE',30000,0,CONCAT('P:\CS511\BTH\Drugstore\WindowsFormsApp1\Food_Picture\','pic26.jpg'))
INSERT INTO FoodItem (FOOD_ID,FOOD_NAME,FOOD_TYPE,FOOD_PRICES,FOOD_NUM_ORDER,URL_FOOD_PICTURE)  VALUES ('027',N'Trà Ô long Kem Phô Mai','BEVERAGE',35000,0,CONCAT('P:\CS511\BTH\Drugstore\WindowsFormsApp1\Food_Picture\','pic27.jpg'))
INSERT INTO FoodItem (FOOD_ID,FOOD_NAME,FOOD_TYPE,FOOD_PRICES,FOOD_NUM_ORDER,URL_FOOD_PICTURE)  VALUES ('028',N'Trà Sữa Hạnh Phúc','BEVERAGE',50000,0,CONCAT('P:\CS511\BTH\Drugstore\WindowsFormsApp1\Food_Picture\','pic28.jpg'))
INSERT INTO FoodItem (FOOD_ID,FOOD_NAME,FOOD_TYPE,FOOD_PRICES,FOOD_NUM_ORDER,URL_FOOD_PICTURE)  VALUES ('029',N'Trà Đào Bưởi Chân Trâu Trắng','BEVERAGE',25000,0,CONCAT('P:\CS511\BTH\Drugstore\WindowsFormsApp1\Food_Picture\','pic29.jpg'))
INSERT INTO FoodItem (FOOD_ID,FOOD_NAME,FOOD_TYPE,FOOD_PRICES,FOOD_NUM_ORDER,URL_FOOD_PICTURE)  VALUES ('030',N'Trà Mận Hạt Sen','BEVERAGE',35000,0,CONCAT('P:\CS511\BTH\Drugstore\WindowsFormsApp1\Food_Picture\','pic30.jpg'))
INSERT INTO FoodItem (FOOD_ID,FOOD_NAME,FOOD_TYPE,FOOD_PRICES,FOOD_NUM_ORDER,URL_FOOD_PICTURE)  VALUES ('031',N'Trà Sữa Dâu','BEVERAGE',40000,0,CONCAT('P:\CS511\BTH\Drugstore\WindowsFormsApp1\Food_Picture\','pic31.jpg'))
INSERT INTO FoodItem (FOOD_ID,FOOD_NAME,FOOD_TYPE,FOOD_PRICES,FOOD_NUM_ORDER,URL_FOOD_PICTURE)  VALUES ('032',N'Trà Sữa Truyền Thống','BEVERAGE',30000,0,CONCAT('P:\CS511\BTH\Drugstore\WindowsFormsApp1\Food_Picture\','pic32.jpg'))





delete from FOOD_ORDERED
